### ISSUE TITLE
Validation-tester says valid but can't load file

### ISSUE THREAD

**Issue by enkelmedia** [Analogy-LogViewer/Analogy.LogViewer.Log4Net#72]
After the updates in https://github.com/Analogy-LogViewer/Analogy.LogViewer.Log4Net/pull/71 I manage to validate my regex against a test-string in the settings window:

![image](https://user-images.githubusercontent.com/1782524/123266463-57834580-d4fc-11eb-9f90-29e4a7601b74.png)

But when trying to load a .log file (Log4Net) this is what the UI is saying:

![image](https://user-images.githubusercontent.com/1782524/123266439-505c3780-d4fc-11eb-9fab-3cae6fda5412.png)

I have tested with several different "types" of log files, one looks like this:

Not Working: All entries on same line:
```
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolving umbraco.cms.businesslogic.macro.IMacroEngine
2021-06-24 09:46:47,303 [171] INFO  Umbraco.Core.PluginManager - Resolved umbraco.cms.businesslogic.macro.IMacroEngine (took 3ms)
2021-06-24 09:50:35,550 [171] ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=ExternalIndexer, NodeId=-1
2021-06-24 09:50:35,599 [171] ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=InternalIndexer, NodeId=-1
```

Not working: Multiple lines per entry

```
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolving umbraco.interfaces.IDiscoverable
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolved umbraco.interfaces.IDiscoverable (took 0ms)
2021-06-24 09:46:47,299 [171] INFO  Umbraco.Core.PluginManager - Resolving umbraco.cms.businesslogic.macro.IMacroEngine
2021-06-24 09:46:47,303 [171] INFO  Umbraco.Core.PluginManager - Resolved umbraco.cms.businesslogic.macro.IMacroEngine (took 3ms)
2021-06-24 09:50:35,550 [171] ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=ExternalIndexer, NodeId=-1
System.Exception: Cannot index queue items, the index is currently locked,, IndexSet: ExternalIndexSet
2021-06-24 09:50:35,599 [171] ERROR UmbracoExamine.DataServices.UmbracoLogService - Provider=InternalIndexer, NodeId=-1
System.Exception: Error indexing queue items,System.IO.IOException: Cannot overwrite: \\foobar\_3bq.tvx
   at Lucene.Net.Store.FSDirectory.InitOutput(String name)
   at Lucene.Net.Store.SimpleFSDirectory.CreateOutput(String name)
   at Lucene.Net.Index.TermVectorsTermsWriter.InitTermVectorsWriter()
   at Lucene.Net.Index.TermVectorsTermsWriter.FinishDocument(PerDoc perDoc)
   at Lucene.Net.Index.DocFieldProcessorPerThread.PerDoc.Finish()
   at Lucene.Net.Index.DocumentsWriter.WaitQueue.WriteDocument(DocWriter doc)
   at Lucene.Net.Index.DocumentsWriter.WaitQueue.Add(DocWriter doc)
   at Lucene.Net.Index.DocumentsWriter.FinishDocument(DocumentsWriterThreadState perThread, DocWriter docWriter)
   at Lucene.Net.Index.DocumentsWriter.UpdateDocument(Document doc, Analyzer analyzer, Term delTerm)
   at Lucene.Net.Index.IndexWriter.UpdateDocument(Term term, Document doc, Analyzer analyzer)
   at Examine.LuceneEngine.Providers.LuceneIndexer.AddDocument(Dictionary`2 fields, IndexWriter writer, Int32 nodeId, String type) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 1382
   at Examine.LuceneEngine.Providers.LuceneIndexer.ProcessIndexQueueItem(IndexOperation op, IndexWriter writer) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 2031
   at Examine.LuceneEngine.Providers.LuceneIndexer.ProcessQueueItem(IndexOperation item, ICollection`1 indexedNodes, IndexWriter writer) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 1732
   at Examine.LuceneEngine.Providers.LuceneIndexer.ForceProcessQueueItems(Boolean block) in C:\projects\examine-qvx04\src\Examine\LuceneEngine\Providers\LuceneIndexer.cs:line 1586, IndexSet: InternalIndexSet
2021-06-24 09:50:39,529 [171] INFO  umbraco.content - Save Xml to file...
2021-06-24 09:50:39,539 [171] INFO  umbraco.content - Saved Xml to file.

```
Not sure what is going wrong here but is there anything that you can se that is wrong?

**Comment by enkelmedia** [comment]
Hmm..

Turns out that this line returns false, with the configured settings `*.1,*.txt,*.log`.

OfflineDataProvider.cs
```
public override bool CanOpenFile(string fileName)
        {
            foreach (string pattern in UserSettingsManager.UserSettings.Settings.SupportFormats)
            {
                if (PatternMatcher.StrictMatchPattern(pattern, fileName))
                {
                    return true;
                }
            }
            return false;
        }
```

Setting supported formats to *.* would load the file

![image](https://user-images.githubusercontent.com/1782524/123268489-5b17cc00-d4fe-11eb-83e1-94a7b741ff3e.png)

**Comment by enkelmedia** [comment]
After getting this in place I can load the file when my pattern is correct =D
